[package]
name = "reaper"
version = "0.2.0"
description = "A simple TUI for listing and killing listening ports"
repository = "https://github.com/aymenkrifa/reaper"
authors = ["aymenkrifa <aymenkrifa@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
